Models/Order.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TMA3A.Models
{
    public class Order
    {
        public enum OrderStatus
        {
            CART,
            ORDERED
        }

        [Display(Name = "Order #")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Display(Name = "Customer")]
        public string? UserId { get; set; }
        public virtual User? User { get; set; }
        public OrderStatus Status { get; set; } = OrderStatus.CART;
        [ValidateNever]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        [Display(Name = "Street")]
        public string? StreetAddress { get; set; }
        public string? City { get; set; }
        public string? State { get; set; }
        [Display(Name = "Postal Code")]
        public string? PostalCode { get; set; }
        public string? Country { get; set; }    
    }
}

Pages/Images/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Images
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public DeleteModel(TMA3A.Data.TMA3AContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Image Image { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null || _context.Image == null)
            {
                return NotFound();
            }

            var image = await _context.Image.FirstOrDefaultAsync(m => m.Location == id);

            if (image == null)
            {
                return NotFound();
            }
            else 
            {
                Image = image;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null || _context.Image == null)
            {
                return NotFound();
            }
            var image = await _context.Image.FindAsync(id);

            if (image != null)
            {
                Image = image;
                _context.Image.Remove(Image);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }

        public IActionResult OnGetAll(string id)
        {
            List<Image> AllImages = _context.Image.ToList();
            _context.Image.RemoveRange(AllImages);
            _context.SaveChanges();
            return RedirectToPage("./Index");
        }
    }
}

Pages/Images/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Images
{
    [Authorize(Roles = "Admin")]
    public class DetailsModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public DetailsModel(TMA3A.Data.TMA3AContext context)
        {
            _context = context;
        }

      public Image Image { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null || _context.Image == null)
            {
                return NotFound();
            }

            var image = await _context.Image.FirstOrDefaultAsync(m => m.Location == id);
            if (image == null)
            {
                return NotFound();
            }
            else 
            {
                Image = image;
            }
            return Page();
        }
    }
}

Pages/Orders/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Orders
{
    public class DeleteModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public DeleteModel(TMA3A.Data.TMA3AContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Order Order { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order.FirstOrDefaultAsync(m => m.Id == id);

            if (order == null)
            {
                return NotFound();
            }
            else 
            {
                Order = order;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }
            var order = await _context.Order.FindAsync(id);

            if (order != null)
            {
                Order = order;
                _context.Order.Remove(Order);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Orders/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Orders
{
    public class DetailsModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public DetailsModel(TMA3A.Data.TMA3AContext context)
        {
            _context = context;
        }

        public decimal SubTotal 
        { get
            {
                if (Order == null)
                {
                    return 0M;
                }
                
                decimal outData = 0M;
                foreach(var orderLine in Order.OrderLines)
                {
                    outData += (decimal)((float)orderLine.Product.Price * orderLine.Qty);
                }
                return outData;
            } 
        }

        public Order Order { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order.Include(b => b.OrderLines)
                .ThenInclude(c=>c.Product)
                .Include(b=>b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }
            else
            { 
                Order = order;
            }
            return Page();
        }

        public IActionResult OnPostSubmit(int? id)
        {
            _context.Order.Include(b => b.OrderLines)
                .ThenInclude(c => c.Product);
            Order? order = _context.Order.Include(b => b.OrderLines)
                .ThenInclude(c => c.Product).FirstOrDefault(d=>d.Id == id);
            if (order == null) { RedirectToPage("Orders/Index"); }
            order.Status = Order.OrderStatus.ORDERED;
            Order = order;
            _context.SaveChanges();
            return Page();
        }
    }
}

Pages/Orders/EditShipping.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Orders
{
    public class EditShippingModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        [BindProperty]
        public InputModel Input { get; set; }
        public EditShippingModel(TMA3AContext context)
        {
            _context = context;
        }
        public IActionResult OnGet(int? orderId)
        {
            Order? order = _context.Order.Find(orderId);
            if (order == null)
            {
                return RedirectToPage("/PartPicker/Index");
            }
            Input = new InputModel
            {
                orderId = order.Id,
                StreetAddress = order.StreetAddress,
                City = order.City,
                PostalCode = order.PostalCode,
                Country = order.Country,
            };
            return Page();
        }
        public IActionResult OnPost()
        {
            Order? order = _context.Order.Find(Input.orderId);
            if (order == null || order.Status == Order.OrderStatus.ORDERED)
            {
                return Redirect("/");
            } else
            {

            }
            order.StreetAddress = Input.StreetAddress;
            order.City = Input.City;
            order.State = Input.State;
            order.PostalCode = Input.PostalCode;
            order.Country = Input.Country;
            _context.SaveChanges();
            return RedirectToPage("/Orders/Details", new {id=order.Id});
        }
        public class InputModel
        {
            public int? orderId { get; set; }
            public string? StreetAddress { get; set; }
            public string? City { get; set; }
            public string? State { get; set; }
            public string? PostalCode { get; set; }
            public string? Country { get; set; }
        }
    }
}

Pages/Orders/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Orders
{
    public class IndexModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;
        private readonly UserManager<User> _userManager;

        public User? CurrentUser { get; set; }

        [BindProperty(SupportsGet = true)]
        public int? SearchString { get; set; } = null;

        public IndexModel(TMA3A.Data.TMA3AContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IList<Order> Order { get;set; } = default!;

        public async Task<IActionResult> OnGetAsync()
        {
            var user = _userManager.GetUserId(User);
            CurrentUser = _context.User.Find(user);

            IList<Order> allOrder = await _context.Order
                .Include(o => o.User)
                .Include(o => o.OrderLines)
                .ThenInclude(b => b.Product).ToListAsync();
            if (_context.Order != null && CurrentUser != null)
            {
                var oq = from o in allOrder
                         where o.UserId == CurrentUser.Id
                         select o;
                Order = oq.ToList();
            } else if(SearchString is not null)
            {
                var oq = from o in allOrder
                         where o.Id == SearchString && o.UserId is null
                         select o;
                Order = oq.ToList();
                if (Order.Count == 0)
                {
                    ViewData["DoesNotExist"] = $"Order# {SearchString} does not exist or the order is for a registered user. Ensure you are logged in with the correct account.";
                    return Page();
                }
            }
            return Page();
        }
    }
}

Pages/Products/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Products
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public DeleteModel(TMA3A.Data.TMA3AContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Product Product { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FirstOrDefaultAsync(m => m.Id == id);

            if (product == null)
            {
                return NotFound();
            }
            else 
            {
                Product = product;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }
            var product = await _context.Product.FindAsync(id);

            if (product != null)
            {
                Product = product;
                _context.Product.Remove(Product);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Products/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Products
{
    [Authorize(Roles = "Admin")]
    public class DetailsModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public DetailsModel(TMA3A.Data.TMA3AContext context)
        {
            _context = context;
        }

      public Product Product { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            else 
            {
                Product = product;
            }
            return Page();
        }
    }
}

Pages/Orders/Delete.cshtml
@page
@model TMA3A.Pages.Orders.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order# @Model.Order.Id</h4>
    <hr />
    <a asp-page="./Index">Back to List</a> |
    <a asp-page="/Orders/Details" asp-route-id="@Model.Order.Id">Details</a>
    <form method="post">
        <input type="hidden" asp-for="Order.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />      
    </form>
</div>

Pages/Orders/Details.cshtml
@page
@model TMA3A.Pages.Orders.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Order# @Html.DisplayFor(model => model.Order.Id)</h4>
    <div class="row">
        <div class="col-sm justify-content-start">
            @if(Model.Order.Status != Models.Order.OrderStatus.ORDERED)
            {
                <p>Check the details below and click "Submit Order" to process.</p>
            }

        </div>
    </div>
    <hr />
    @{
        string rowClass = "bg-warning";
    }
    @if(Model.Order.Status == Models.Order.OrderStatus.ORDERED)
    {
        rowClass = "bg-success";
    } 
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.Status)
        </dt>
        <dd class="col-sm-10 @rowClass">
            @Html.DisplayFor(model => model.Order.Status)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.User)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.User.UserName)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            Shipping Info
        </dt>
        <dd class="col-sm-10">
            @if(Model.Order.Status != Models.Order.OrderStatus.ORDERED)
            {
                <a asp-page="/Orders/EditShipping" asp-route-orderid="@Model.Order.Id">Edit Address</a>
            }
            <table class="table">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Order.StreetAddress)</th>
                        <th>@Html.DisplayNameFor(model => model.Order.City)</th>
                        <th>@Html.DisplayNameFor(model => model.Order.State)</th>
                        <th>@Html.DisplayNameFor(model => model.Order.PostalCode)</th>
                        <th>@Html.DisplayNameFor(model => model.Order.Country)</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Html.DisplayFor(model => model.Order.StreetAddress)</td>
                        <td>@Html.DisplayFor(model => model.Order.City)</td>
                        <td>@Html.DisplayFor(model => model.Order.State)</td>
                        <td>@Html.DisplayFor(model => model.Order.PostalCode)</td>
                        <td>@Html.DisplayFor(model => model.Order.Country)</td>
                    </tr>
                </tbody>
            </table>
        </dd>
    </dl>
    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => Model.Order.OrderLines.First().Product.Title)</th>
                <th>@Html.DisplayNameFor(model => Model.Order.OrderLines.First().Product.Description)</th>
                <th>@Html.DisplayNameFor(model => Model.Order.OrderLines.First().Qty)</th>
                <th>@Html.DisplayNameFor(model => Model.Order.OrderLines.First().Price)</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var orderLines in Model.Order.OrderLines)
            {
                <tr>
                    <td>@Html.DisplayFor(model=>orderLines.Product.Title)</td>
                    <td>@Html.DisplayFor(model=>orderLines.Product.Description)</td>
                    <td>@Html.DisplayFor(model=>orderLines.Qty)</td>
                    <td>@Html.DisplayFor(model=>orderLines.Price)</td>
                </tr>
            }
            <tr>
                <td colspan="4"><hr /></td>
            </tr>
            <tr>
                <td class="fw-bold">Total:</td>
                <td></td>
                <td></td>
                <td class="fw-bold">$ @Model.SubTotal</td>
            </tr>
        </tbody>
    </table>
    

</div>
<div class="row">
    <div class="col-sm">
    @if(Model.Order.Status != Models.Order.OrderStatus.ORDERED)
    {
        <a asp-area="" asp-page="/PartPicker/Index" asp-route-orderid="@Model.Order?.Id">Edit</a> @:|
    }
        <a asp-page="/Orders/Delete" asp-route-id="@Model.Order.Id">Delete</a> |
        <a asp-page="./Index">Back to List</a>
    @if(Model.Order.Status != Models.Order.OrderStatus.ORDERED)
    {
        <form method="post" asp-page-handler="Submit" asp-route-id="@Model.Order.Id">
            <input class="btn btn-primary" type="submit" value="Submit Order"/>
        </form>
    }
    </div>
</div>

Pages/Orders/EditShipping.cshtml
@page
@model TMA3A.Pages.Orders.EditShippingModel
@{
    ViewData["Title"] = "Edit Shipping";
}

<h1>Enter Shipping Address</h1>
<form method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <h4>
        Order# @Html.DisplayFor(model=>model.Input.orderId)
    </h4>
    <input type="hidden" asp-for="Input.orderId"/>
    <div class="row">
        <div class="col-sm">
            <div class="form-group p-1">
                <label asp-for="Input.StreetAddress" class="control-label"></label>
                <input asp-for="Input.StreetAddress" class="form-control" />
                <span asp-validation-for="Input.StreetAddress" class="text-danger"></span>
            </div>
            <div class="form-group p-1">
                <label asp-for="Input.City" class="control-label"></label>
                <input asp-for="Input.City" class="form-control" />
                <span asp-validation-for="Input.City" class="text-danger"></span>
            </div>
            <div class="form-group p-1">
                <label asp-for="Input.State" class="control-label"></label>
                <input asp-for="Input.State" class="form-control" />
                <span asp-validation-for="Input.State" class="text-danger"></span>
            </div>
            <div class="form-group p-1">
                <label asp-for="Input.PostalCode" class="control-label"></label>
                <input asp-for="Input.PostalCode" class="form-control" />
                <span asp-validation-for="Input.PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group p-1">
                <label asp-for="Input.Country" class="control-label"></label>
                <input asp-for="Input.Country" class="form-control" />
                <span asp-validation-for="Input.Country" class="text-danger"></span>
            </div>
            <div class="form-group p-1">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

Pages/Orders/Index.cshtml
@page
@using TMA3A.Models
@model TMA3A.Pages.Orders.IndexModel

@{
    ViewData["Title"] = "Index";
}

@if(Model.Order is not null && Model.Order.Count() > 0)
{
    <h1>Index</h1>

<p>
    <a asp-page="/PartPicker/Index">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Order[0].User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order[0].Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order[0].Status)
            </th>
            <th>
                Total
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Order) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.User.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>

            @{
                decimal outData = 0M;
                foreach(OrderLine orderLine in item.OrderLines)
                {
                    outData += (decimal)((float)orderLine.Product.Price * orderLine.Qty);
                }
            }
            <td>
               $ @outData
            </td>
            <td>
                @if(item.Status != Models.Order.OrderStatus.ORDERED)
                {
                    <a asp-area="" asp-page="/PartPicker/Index" asp-route-orderid="@item.Id">Edit</a> @:| 
                }
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
} else
{
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <form method="get">
                    <h5>You are not logged in. Create an account and login to manage all orders or enter your Order Id below:</h5>
                    @if (ViewData["DoesNotExist"] is not null)
                    {
                        <p class="text text-danger">Order# @Model.SearchString does not exist or the order is for a registered user. 
                            Ensure you are logged in with the correct account.
                        </p>
                        <p>
                            <a asp-page="/PartPicker/Index">New Order</a>
                        </p>
                        <p>
                            <a asp-page="/Identity/Account/Login">Login</a>
                        </p>
                    }
                    <div class="form-group p-1">
                        <label asp-for="SearchString" class="control-label">Enter Order Id:</label>
                        <input asp-for="SearchString" class="form-control" />
                        <span asp-validation-for="SearchString" class="text-danger"></span>
                    </div>
                    <div class="form-group p-1">
                        <input type="submit" value="Search" class="btn btn-primary" />
                    </div>
                </form>
            </div>
            <div class="col-sm"></div>
        </div>
    </div>

}