Models/Image.cs
using System.ComponentModel.DataAnnotations;

namespace TMA3A.Models
{
    public class Image
    {
        [Required]
        [Key]
        public string Location { get; set; }

        public string Name { get; set; } = String.Empty;

        public string Description { get; set; } = String.Empty;

    }
}

Pages/Images/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Images
{
    [Authorize(Roles = "Admin")]
    public class CreateModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public CreateModel(TMA3A.Data.TMA3AContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Image Image { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Image == null || Image == null)
            {
                return Page();
            }

            _context.Image.Add(Image);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Images/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Images
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public DeleteModel(TMA3A.Data.TMA3AContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Image Image { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null || _context.Image == null)
            {
                return NotFound();
            }

            var image = await _context.Image.FirstOrDefaultAsync(m => m.Location == id);

            if (image == null)
            {
                return NotFound();
            }
            else 
            {
                Image = image;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null || _context.Image == null)
            {
                return NotFound();
            }
            var image = await _context.Image.FindAsync(id);

            if (image != null)
            {
                Image = image;
                _context.Image.Remove(Image);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }

        public IActionResult OnGetAll(string id)
        {
            List<Image> AllImages = _context.Image.ToList();
            _context.Image.RemoveRange(AllImages);
            _context.SaveChanges();
            return RedirectToPage("./Index");
        }
    }
}

Pages/Images/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Images
{
    [Authorize(Roles = "Admin")]
    public class DetailsModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public DetailsModel(TMA3A.Data.TMA3AContext context)
        {
            _context = context;
        }

      public Image Image { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null || _context.Image == null)
            {
                return NotFound();
            }

            var image = await _context.Image.FirstOrDefaultAsync(m => m.Location == id);
            if (image == null)
            {
                return NotFound();
            }
            else 
            {
                Image = image;
            }
            return Page();
        }
    }
}

Pages/Images/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Images
{
    [Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public string Location;

        public EditModel(TMA3A.Data.TMA3AContext context, IConfiguration configuration)
        {
            _context = context;
            Location = configuration.GetSection("ImageSlidesConfig")
            .GetSection("Location").Value;
        }

        [BindProperty]
        public Image Image { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null || _context.Image == null)
            {
                return NotFound();
            }

            var image =  await _context.Image.FirstOrDefaultAsync(m => m.Location == id);
            if (image == null)
            {
                return NotFound();
            }
            Image = image;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Image).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ImageExists(Image.Location))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ImageExists(string id)
        {
          return (_context.Image?.Any(e => e.Location == id)).GetValueOrDefault();
        }
    }
}

Pages/Images/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Images
{
    [Authorize(Roles = "Admin")]
    public class IndexModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public string Location;

        public IndexModel(TMA3A.Data.TMA3AContext context, IConfiguration configuration)
        {
            _context = context;
            Location = configuration.GetSection("ImageSlidesConfig")
                        .GetSection("Location").Value;
        }

        public IList<Image> Image { get;set; } = default!;

        public async Task OnGetAsync()
        {
            //Fetch all files in the Folder (Directory).
            Image = _context.Image.ToList();
        }
    }
}

Pages/Images/Show.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TMA3A.Data;
namespace TMA3A.Pages.Images
{
    public class ShowModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;
        public string ImageFolderPath=String.Empty;
        public record ImageRecord
        {
            public string FullPath { get; init; }
            public string Name { get; init; }
            public string Description { get; init; }
        };

        public ShowModel(TMA3AContext context, IConfiguration configuration)
        {
            _context = context;
            ImageFolderPath = configuration.GetSection("ImageSlidesConfig")
                       .GetSection("Location").Value;
        }

        public IList<ImageRecord> Images { get; set; } = new List<ImageRecord>();

        public void OnGet()
        {
            var images = _context.Image.ToList();
            foreach (var image in images)
            {
                string fullPath = $"{ImageFolderPath}/{image.Location}";
                Images.Add(new ImageRecord
                {
                    FullPath = fullPath,
                    Name = image.Name,
                    Description = image.Description
                });
                
            }
        }
    }
}

Pages/Orders/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Orders
{
    public class DeleteModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public DeleteModel(TMA3A.Data.TMA3AContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Order Order { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order.FirstOrDefaultAsync(m => m.Id == id);

            if (order == null)
            {
                return NotFound();
            }
            else 
            {
                Order = order;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }
            var order = await _context.Order.FindAsync(id);

            if (order != null)
            {
                Order = order;
                _context.Order.Remove(Order);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Orders/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Orders
{
    public class DetailsModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public DetailsModel(TMA3A.Data.TMA3AContext context)
        {
            _context = context;
        }

        public decimal SubTotal 
        { get
            {
                if (Order == null)
                {
                    return 0M;
                }
                
                decimal outData = 0M;
                foreach(var orderLine in Order.OrderLines)
                {
                    outData += (decimal)((float)orderLine.Product.Price * orderLine.Qty);
                }
                return outData;
            } 
        }

        public Order Order { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order.Include(b => b.OrderLines)
                .ThenInclude(c=>c.Product)
                .Include(b=>b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }
            else
            { 
                Order = order;
            }
            return Page();
        }

        public IActionResult OnPostSubmit(int? id)
        {
            _context.Order.Include(b => b.OrderLines)
                .ThenInclude(c => c.Product);
            Order? order = _context.Order.Include(b => b.OrderLines)
                .ThenInclude(c => c.Product).FirstOrDefault(d=>d.Id == id);
            if (order == null) { RedirectToPage("Orders/Index"); }
            order.Status = Order.OrderStatus.ORDERED;
            Order = order;
            _context.SaveChanges();
            return Page();
        }
    }
}

Pages/Products/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Products
{
    [Authorize(Roles = "Admin")]
    public class CreateModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public CreateModel(TMA3A.Data.TMA3AContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Product Product { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Product == null || Product == null)
            {
                return Page();
            }

            _context.Product.Add(Product);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Products/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Products
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public DeleteModel(TMA3A.Data.TMA3AContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Product Product { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FirstOrDefaultAsync(m => m.Id == id);

            if (product == null)
            {
                return NotFound();
            }
            else 
            {
                Product = product;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }
            var product = await _context.Product.FindAsync(id);

            if (product != null)
            {
                Product = product;
                _context.Product.Remove(Product);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Products/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TMA3A.Data;
using TMA3A.Models;

namespace TMA3A.Pages.Products
{
    [Authorize(Roles = "Admin")]
    public class DetailsModel : PageModel
    {
        private readonly TMA3A.Data.TMA3AContext _context;

        public DetailsModel(TMA3A.Data.TMA3AContext context)
        {
            _context = context;
        }

      public Product Product { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            else 
            {
                Product = product;
            }
            return Page();
        }
    }
}

Pages/Images/Create.cshtml
@page
@model TMA3A.Pages.Images.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Image</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Image.Location" class="control-label"></label>
                <input asp-for="Image.Location" class="form-control" />
                <span asp-validation-for="Image.Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image.Name" class="control-label"></label>
                <input asp-for="Image.Name" class="form-control" />
                <span asp-validation-for="Image.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image.Description" class="control-label"></label>
                <input asp-for="Image.Description" class="form-control" />
                <span asp-validation-for="Image.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Images/Delete.cshtml
@page
@model TMA3A.Pages.Images.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Image</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Image.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Image.Description)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Image.Location" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Images/Details.cshtml
@page
@model TMA3A.Pages.Images.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Image</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image.Location)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Image.Location)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Image.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Image.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Image?.Location">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Images/Edit.cshtml
@page
@model TMA3A.Pages.Images.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Image</h4>
<hr />
<div class="row">
    <div class="col-md">
      <img 
        class="img-fluid" 
        src="~/@($"{Model.Location}/{Model.Image.Location}")"
        style="max-width:50%;max-height:auto;"
        >
    </div>
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Image.Location" readonly/>
            <div class="form-group">
                <label asp-for="Image.Name" class="control-label"></label>
                <input asp-for="Image.Name" class="form-control" />
                <span asp-validation-for="Image.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image.Description" class="control-label"></label>
                <input asp-for="Image.Description" class="form-control" />
                <span asp-validation-for="Image.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Images/Index.cshtml
@page
@model TMA3A.Pages.Images.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<p>
    <a asp-page="Show">Show slideshow</a>
</p>
<p>
    <a asp-page="Delete" asp-page-handler="All">Delete</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Image
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image[0].Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image[0].Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Image) {
        <tr>
            <td>
               <img 
                class="img-fluid" 
                src="~/@($"{Model.Location}/{item.Location}")"
                style="max-width:50%;max-height:auto;"
               >
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.Location">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.Location">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Location">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Pages/Images/Show.cshtml
@page
@model TMA3A.Pages.Images.ShowModel
@{
}
<div class="row slide-container">
    <div class="col-xl"></div>
    <div class="col-xl">
        <div class="control-container row">
            <div class="col-sm">
                <div id="sequential-controller">
                    <button style="display:none;" id="start-show" type="button" class="btn btn-success slideshow-control mt-2">Start Show</button>
                    <button id="stop-show" type="button" class="btn btn-danger slideshow-control mt-2">Stop Show</button>
                </div>
            </div>
            <div class="col-sm">
                <div class="form-group" id="slideshow-mode">
                    <label for="slideshow-mode">Slideshow Mode</label>
                    <select class="form-control" id="show-mode">
                        <option selected>Sequential</option>
                        <option>Random</option>
                    </select>
                </div>
            </div>
            <div class="col-sm">
                <div class="form-group" id="sequential-mode-container">
                    <label for="sequential-mode-container">Sequence Mode</label>
                    <select class="form-control" id="sequential-mode">
                        <option selected>Forward</option>
                        <option>Backward</option>
                    </select>
                </div>
            </div>
        </div>
        <div id="slideshow-container" class="carousel slide b-2 border-1 border-dark rounded" data-bs-ride="carousel">
            
            <div class="carousel-inner">
            @{
                int counter = 0;
            }
            @foreach(var img in Model.Images)
            {
                var imgClass = counter == 0 ? "carousel-item active": "carousel-item";
                <div class="@imgClass">        
                    <img 
                    class="img-fluid slide-image" 
                    src="~/@img.FullPath" 
                    >
                    <div class="carousel-caption">
                        <h6>[@(counter+1)] @img.Name</h6>
                        <p>@img.Description</p>
                    </div>
                </div>
                counter++;
            }
            </div>
            <button style="visibility:hidden" class="carousel-control-prev" type="button" data-bs-target="#slideshow-container" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button style="visibility:hidden" class="carousel-control-next" type="button" data-bs-target="#slideshow-container" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
            
        </div>
        
    </div>  
    <div class="col-xl"></div>
</div>

@section Scripts {
    <script src="~/js/Slide.js"></script>
}